# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  opencti-latest = {
    pname = "opencti-latest";
    version = "b0fb1431c0fb9a1ec6a27c741803fda3dd31297f";
    src = fetchFromGitHub ({
      owner = "OpenCTI-Platform";
      repo = "opencti";
      rev = "b0fb1431c0fb9a1ec6a27c741803fda3dd31297f";
      fetchSubmodules = false;
      sha256 = "sha256-0u7jb2o3UKSEhym+VGIg0g/y9d6Uz97nC1YeszZLN30=";
    });
    date = "2022-11-05";
  };
  opencti-release = {
    pname = "opencti-release";
    version = "5.3.17";
    src = fetchFromGitHub ({
      owner = "OpenCTI-Platform";
      repo = "opencti";
      rev = "5.3.17";
      fetchSubmodules = false;
      sha256 = "sha256-2HreEl5+49EGVkHpclEMEtYcl2qjN8JTFKRzcKZlxOs=";
    });
  };
}
