# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  opencti = {
    pname = "opencti";
    version = "5.4.1";
    src = fetchFromGitHub ({
      owner = "OpenCTI-Platform";
      repo = "opencti";
      rev = "5.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-p1RBnQcEVHevNHEiZ2RsxMeWi4o6B0dUxmAgChikiw8=";
    });
  };
  opencti-latest = {
    pname = "opencti-latest";
    version = "51c2ea90933804cdda874844cc888261d2e13510";
    src = fetchFromGitHub ({
      owner = "OpenCTI-Platform";
      repo = "opencti";
      rev = "51c2ea90933804cdda874844cc888261d2e13510";
      fetchSubmodules = false;
      sha256 = "sha256-p1RBnQcEVHevNHEiZ2RsxMeWi4o6B0dUxmAgChikiw8=";
    });
    date = "2022-11-24";
  };
}
